// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Be.Ugent;
#pragma warning restore 0105

namespace Be.Ugent
{
    public static partial class SpatialCodecsInterop
    {
        public const string NativeLib = "spatial_codecs";

        static SpatialCodecsInterop()
        {
        }


        /// Return the last error message for the calling thread (null-terminated).
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "pc_last_error_message")]
        public static extern IntPtr pc_last_error_message();

        /// Clear last error for the calling thread.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "pc_clear_last_error")]
        public static extern void pc_clear_last_error();

        /// Create a decoder handle (owning an internal `Vec<GaussianSplatF32>` reused across runs).
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "pc_gsplat_decoder_create")]
        public static extern PcStatus pc_gsplat_decoder_create(ref IntPtr out_handle);

        /// Free a decoder handle (safe to call with null).
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "pc_gsplat_decoder_free")]
        public static extern void pc_gsplat_decoder_free(IntPtr handle);

        /// Decode bytes into the decoder’s internal `Vec<GaussianSplatF32>`.
        /// Returns meta with count; bounds are produced in `pc_gsplat_decoder_write_to_buffers`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "pc_gsplat_decoder_decode_from_bytes")]
        public static extern PcStatus pc_gsplat_decoder_decode_from_bytes(IntPtr handle, Sliceu8 data, out PcGsplatMeta out_meta);

        /// Decode bytes into the decoder’s internal `Vec<GaussianSplatF32>`.
        /// Returns meta with count; bounds are produced in `pc_gsplat_decoder_write_to_buffers`.
        public static PcStatus pc_gsplat_decoder_decode_from_bytes(IntPtr handle, byte[] data, out PcGsplatMeta out_meta)
        {
            var data_pinned = GCHandle.Alloc(data, GCHandleType.Pinned);
            var data_slice = new Sliceu8(data_pinned, (ulong) data.Length);
            try
            {
                return pc_gsplat_decoder_decode_from_bytes(handle, data_slice, out out_meta);;
            }
            finally
            {
                data_pinned.Free();
            }
        }

        /// Convert decoded splats into caller-provided output buffers.
        /// Writes the first N elements (N = last decoded `splat_count`).
        /// Also computes bounds and returns them in `out_meta`.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "pc_gsplat_decoder_write_to_buffers")]
        public static extern PcStatus pc_gsplat_decoder_write_to_buffers(IntPtr handle, PcGsplatOutBuffers out_buffers, out PcGsplatMeta out_meta);

    }

    /// Status codes for FFI calls.
    public enum PcStatus
    {
        Ok = 0,
        NullPointer = 1,
        InvalidSlice = 2,
        DecodeFailed = 3,
        SizeOverflow = 4,
        Panic = 5,
    }

    /// Metadata (count always valid after decode; bounds valid after write_to_buffers).
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PcGsplatMeta
    {
        public uint splat_count;
        public byte sh_bands;
        public byte _reserved0;
        public ushort _reserved1;
        public PcVec3 bounds_center;
        public PcVec3 bounds_extents;
    }

    /// Caller-provided output buffers (AoS arrays).
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PcGsplatOutBuffers
    {
        public PcMutSliceVec3 positions;
        public PcMutSliceVec4 colors;
        public PcMutSliceVec3 scales;
        public PcMutSliceVec4 rotations;
    }

    /// Mutable slice for `PcVec3` output.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PcMutSliceVec3
    {
        public IntPtr data;
        public ulong len;
    }

    /// Mutable slice for `PcVec4` output.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PcMutSliceVec4
    {
        public IntPtr data;
        public ulong len;
    }

    /// 3-float vector (Unity `Vector3` compatible layout).
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PcVec3
    {
        public float x;
        public float y;
        public float z;
    }

    /// 4-float vector (Unity `Vector4` compatible layout).
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct PcVec4
    {
        public float x;
        public float y;
        public float z;
        public float w;
    }

    ///A pointer to an array of data someone else owns which may not be modified.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Sliceu8
    {
        ///Pointer to start of immutable data.
        IntPtr data;
        ///Number of elements.
        ulong len;
    }

    public partial struct Sliceu8 : IEnumerable<byte>
    {
        public Sliceu8(GCHandle handle, ulong count)
        {
            this.data = handle.AddrOfPinnedObject();
            this.len = count;
        }
        public Sliceu8(IntPtr handle, ulong count)
        {
            this.data = handle;
            this.len = count;
        }
        public byte this[int i]
        {
            get
            {
                if (i >= Count) throw new IndexOutOfRangeException();
                var size = Marshal.SizeOf(typeof(byte));
                var ptr = new IntPtr(data.ToInt64() + i * size);
                return Marshal.PtrToStructure<byte>(ptr);
            }
        }
        public byte[] Copied
        {
            get
            {
                var rval = new byte[len];
                for (var i = 0; i < (int) len; i++) {
                    rval[i] = this[i];
                }
                return rval;
            }
        }
        public int Count => (int) len;
        public IEnumerator<byte> GetEnumerator()
        {
            for (var i = 0; i < (int)len; ++i)
            {
                yield return this[i];
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }




    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
