[package]
name = "cdn_proxy"
version = "0.1.0"
edition = "2021"

[features]
default = []  # Default features, keep it empty to disable by default
console-tracing = []  # Feature flag for console tracing

[dependencies]
axum = { workspace = true, features = ["ws"]}
axum-server = { version = "0.8", features = ["tls-rustls"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "time", "fs", "io-util"] }
tokio-util.workspace = true
tokio-stream = "0.1"
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"] }
tower-http = { workspace = true, features = ["cors", "fs", "trace"] }
tower.workspace = true
futures-util = "0.3"
http-body-util = "0.1"

bytes = "1"
clap = { workspace = true, features = ["derive", "env"] }
dashmap.workspace = true
blake3 = "1.5"
moka = { version = "0.12", features = ["future"] }

reqwest = { workspace = true, default-features = false, features = ["rustls-tls", "http2", "stream"] }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror = "1.0"

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

url.workspace = true
hex = "0.4"

[dev-dependencies]
reqwest = { workspace = true, default-features = false, features = ["rustls-tls", "http2"] }
