// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Be.Ugent;
#pragma warning restore 0105

namespace Be.Ugent
{
    public static partial class ReceiverInteropClass
    {
        public const string NativeLib = "libpc_receiver";

        static ReceiverInteropClass()
        {
        }


        /// Returns the version of this API.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "version")]
        public static extern uint version();

        /// Registers a callback for logging messages to the application that uses this library.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "register_debug_callback")]
        public static extern void register_debug_callback(DebugCallback callback);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "unregister_debug_callback")]
        public static extern void unregister_debug_callback();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "init")]
        public static extern void init(uint log_level, string server_url, string multicast_url);

        /// Get the list of stream IDs.
        /// This function returns all active stream IDs as a vector of strings.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "get_stream_ids")]
        public static extern void get_stream_ids(InteropDelegate_fn_pconst_i8 callback);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ingress_subscribe")]
        public static extern void ingress_subscribe(SubscriptionCallback callback);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ingress_unsubscribe")]
        public static extern void ingress_unsubscribe();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "consume_frame")]
        public static extern bool consume_frame(Sliceu8 stream_id);

    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void InteropDelegate_fn_pconst_i8(ref sbyte x0);

    ///A pointer to an array of data someone else owns which may not be modified.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Slicef32
    {
        ///Pointer to start of immutable data.
        IntPtr data;
        ///Number of elements.
        ulong len;
    }

    public partial struct Slicef32 : IEnumerable<float>
    {
        public Slicef32(GCHandle handle, ulong count)
        {
            this.data = handle.AddrOfPinnedObject();
            this.len = count;
        }
        public Slicef32(IntPtr handle, ulong count)
        {
            this.data = handle;
            this.len = count;
        }
        public float this[int i]
        {
            get
            {
                if (i >= Count) throw new IndexOutOfRangeException();
                var size = Marshal.SizeOf(typeof(float));
                var ptr = new IntPtr(data.ToInt64() + i * size);
                return Marshal.PtrToStructure<float>(ptr);
            }
        }
        public float[] Copied
        {
            get
            {
                var rval = new float[len];
                for (var i = 0; i < (int) len; i++) {
                    rval[i] = this[i];
                }
                return rval;
            }
        }
        public int Count => (int) len;
        public IEnumerator<float> GetEnumerator()
        {
            for (var i = 0; i < (int)len; ++i)
            {
                yield return this[i];
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }


    ///A pointer to an array of data someone else owns which may not be modified.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Sliceu8
    {
        ///Pointer to start of immutable data.
        IntPtr data;
        ///Number of elements.
        ulong len;
    }

    public partial struct Sliceu8 : IEnumerable<byte>
    {
        public Sliceu8(GCHandle handle, ulong count)
        {
            this.data = handle.AddrOfPinnedObject();
            this.len = count;
        }
        public Sliceu8(IntPtr handle, ulong count)
        {
            this.data = handle;
            this.len = count;
        }
        public byte this[int i]
        {
            get
            {
                if (i >= Count) throw new IndexOutOfRangeException();
                var size = Marshal.SizeOf(typeof(byte));
                var ptr = new IntPtr(data.ToInt64() + i * size);
                return Marshal.PtrToStructure<byte>(ptr);
            }
        }
        public byte[] Copied
        {
            get
            {
                var rval = new byte[len];
                for (var i = 0; i < (int) len; i++) {
                    rval[i] = this[i];
                }
                return rval;
            }
        }
        public int Count => (int) len;
        public IEnumerator<byte> GetEnumerator()
        {
            for (var i = 0; i < (int)len; ++i)
            {
                yield return this[i];
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }


    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void DebugCallback(string message, string log_level);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void SubscriptionCallback(ulong send_time, ulong presentation_time, ulong error_count, ulong point_count, Slicef32 coordinates, Sliceu8 colors, string stream_id);



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
