[package]
name = "shared_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
spatial_utils.workspace = true
webrtc.workspace = true
bytes.workspace = true
serde.workspace = true
async-trait.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true
dashmap.workspace = true
circular-buffer.workspace = true
bitvec.workspace = true
rustls.workspace = true
