services:
  prometheus_xr:
    image: prom/prometheus:latest
    container_name: prometheus_xr
    volumes:
      - ./prometheus_data:/etc/prometheus
    ports:
      - "9090:9090"

  grafana_xr:
    image: grafana/grafana:latest
    container_name: grafana_xr
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_provisioning:/etc/grafana/provisioning/datasources
    ports:
      # Expose the grafana (3000) website so that we
      # can access it from the host machine using localhost:9091
      - "9091:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=XRforAll
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
