[package]
name = "draco-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
tracing.workspace = true

[build-dependencies]
cmake = "0.1.51"
bindgen = "0.70.1"