[package]
name = "draco-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]


[[bin]]
name = "draco"
path = "src/main.rs"  # Points to the main.rs file

[dependencies]
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
nalgebra.workspace = true

[build-dependencies]
cmake = "0.1.51"
bindgen = "0.72.0"