[package]
name = "pc-receiver"
version = "0.1.0"
edition = "2021"

[features]
default = []  # Default features, keep it empty to disable by default
console-tracing = []  # Feature flag for console tracing

[dependencies]
spatial_codecs.workspace = true
spatial_utils.workspace = true
pcf.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
futures.workspace = true
rust_socketio = { workspace = true, features = ["async"] }
serde.workspace = true
serde_json.workspace = true
libc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
console-subscriber.workspace = true
interoptopus.workspace = true
interoptopus_backend_csharp.workspace = true
once_cell.workspace = true
clap.workspace = true
rayon.workspace = true
webrtc.workspace = true
flute.workspace = true
url.workspace = true
circular-buffer.workspace = true
dashmap.workspace = true
metrics.workspace = true
abr_core.workspace = true
rbase64.workspace = true
prometheus.workspace = true
shared_networking.workspace = true
shared_utils.workspace = true
dash_player.workspace = true
mp4_box.workspace = true

[lib]
crate-type = ["cdylib", "rlib", "staticlib"] # Allows us to build both a shared library and a Rust library

[[bin]]
name = "pc-receiver"
path = "src/main.rs"  # Points to the main.rs file
